### PR TITLE
Pr fix manage

### LINKED ISSUE #226: Add creating to manage
Make the manage boxes look like the add tab where existing ones are on top and creating is on bottom

### PR DESCRIPTION
**Pull request by alan412**
Fixes #226 and also makes these simpler for the user

### CODE REVIEW

File: src/reactComponents/FileManageModal.tsx [hunk 1]
```diff
@@ -441,6 +456,23 @@ export default function FileManageModal(props: FileManageModalProps) {
...
+          padding: '12px',
+        }}>
+        <ClassNameComponent
+            tabType={props.tabType}
+            newItemName={newItemName}
+            setNewItemName={setNewItemName}
+            onAddNewItem={handleAddNewItem}
+            project={props.project}
+            storage={props.storage}
+            buttonLabel={t('CREATE')}
```
[the remark this answers is not in the document]
Comment (alan412) [reply src/reactComponents/FileManageModal.tsx:473]: There is in the add tab dialog PR.   I didn't create it as well here because I didn't want a merge conflict.

File: src/reactComponents/Menu.tsx [hunk 2]
```diff
@@ -140,8 +112,8 @@ function getMenuItems(t: (key: string) => string, project: storageProject.Projec
     ]),
     getItem(t('EXPLORER'), 'explorer', <FileOutlined />, [
       getItem(t('ROBOT'), project.robot.modulePath, <RobotOutlined />),
```
[the remark this answers is not in the document]
Comment (alan412) [reply src/reactComponents/Menu.tsx:114]: It makes the robot tab the active tab.

[the remark this answers is not in the document]
Comment (lizlooney) [reply src/reactComponents/Menu.tsx:114]: It doesn't work.

[the remark this answers is not in the document]
Comment (alan412) [reply src/reactComponents/Menu.tsx:114]: I am leaving right now, but I found the problem but don't really understand it.   When the app was changed for every tab to have its own blockly, setActiveTab is no longer sufficient to change the tab.   I suspect this may have other problems.

File: src/App.tsx [hunk 3]
```diff
@@ -583,9 +583,14 @@ const AppContent: React.FC<AppContentProps> = ({ project, setProject }): React.J
...
-      setActiveTab(project.robot.modulePath);
+      
+      // Only set active tab to robot if no active tab is set or if the current active tab no longer exists
+      const currentActiveTabExists = tabs.some(tab => tab.key === activeTab);
+      if (!activeTab || !currentActiveTabExists) {
+        setActiveTab(project.robot.modulePath);
+      }
     }
-  }, [modulePathToContentText]);
+  }, [modulePathToContentText, activeTab]);
```
Comment (lizlooney) [inline src/App.tsx:593]: I don't understand this change. According to the comment on line 581 "Update tab items when fetching modules is done", the purpose of this code is to update the tab items and to set the active tab to the robot.

I don't know why you've added activeTab to line 593.

File: src/reactComponents/Menu.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (lizlooney) [reply src/reactComponents/Menu.tsx:114]: Sometimes it works and sometimes it doesn't work.
If I use the menu (explorer) to change tabs, then the Robot item in the menu works to change back to the Robot tab.
However, if I use the tabs to change tabs, then the Robot item in the menu does not work.
I don't think it was caused by pr 224 (every tab has its own blockly) because I can reproduce after getting my local repo back to before that pr.
I'll file a bug. Don't worry about it for this PR because this PR isn't the cause.

File: src/App.tsx (hunk 3 above)
Comment (alan412) [reply src/App.tsx]: I can't figure out why it is there either.  My best bet is that I added it when I tried something more complicated and forgot to remove it.   I just removed it in another commit.

File: src/App.tsx [hunk 4]
```diff
@@ -586,7 +586,12 @@ const AppContent: React.FC<AppContentProps> = ({ project, setProject }): React.J
     if (project) {
       const tabs = createTabItemsFromProject(project);
       setTabItems(tabs);
-      setActiveTab(project.robot.modulePath);
+
```
[the remark this answers is not in the document]
Comment (alan412) [reply src/App.tsx:589]: This code is needed.   Otherwise whenever you create a new tab, it isn't selected.  Or more correctly, it is selected and then the robot is immediately selected again.

**Comment by alan412** [comment]
I put all of the Manage in its own area and brought back Explorer that looks like a typical IDE

File: src/i18n/locales/en/translation.json [hunk 5]
```diff
@@ -42,6 +43,30 @@
...
+    "FAILED_TO_COPY_MODULE": "Failed to copy module",
+    "MODULE_NOT_FOUND_FOR_COPYING": "Original module not found for copying",
+    "COPY_SUFFIX": "{{name}} (copy)",
+    "DELETE_MODULE_CONFIRM": "Delete {title}?",
+    "MANAGEMENT": "Management",
+    "TYPE_MANAGEMENT": "{{type}} Management",
+    "RENAME_TYPE_TITLE": "Rename {{type}}: {{title}}",
+    "COPY_TYPE_TITLE": "Copy {{type}}: {{title}}",
+    "RENAME": "Rename",
+    "NO_FILES_FOUND": "No {type} files found",
```
Comment (lizlooney) [inline src/i18n/locales/en/translation.json:69]: {type} -> {{type}}

File: src/i18n/locales/en/translation.json [hunk 6]
```diff
@@ -42,6 +43,30 @@
...
+    "DELETE_PROJECT_CONFIRM": "Delete {projectName}?",
+    "DELETE_CANNOT_BE_UNDONE": "This action cannot be undone.",
+    "NO_PROJECTS_FOUND": "No projects found",
+    "CREATE_PROJECT_TO_START": "Please create a new project to get started.",
+    "PAGINATION_ITEMS": "{range0}-{range1} of {total} items",
+    "FAILED_TO_RENAME_MODULE": "Failed to rename module",
+    "FAILED_TO_COPY_MODULE": "Failed to copy module",
+    "MODULE_NOT_FOUND_FOR_COPYING": "Original module not found for copying",
+    "COPY_SUFFIX": "{{name}} (copy)",
+    "DELETE_MODULE_CONFIRM": "Delete {title}?",
```
Comment (lizlooney) [inline src/i18n/locales/en/translation.json:63]: {title} -> {{title}}

File: src/i18n/locales/en/translation.json [hunk 7]
```diff
@@ -42,6 +43,30 @@
...
     "COPY": "Copy",
+    "FAILED_TO_RENAME_PROJECT": "Failed to rename project",
+    "FAILED_TO_COPY_PROJECT": "Failed to copy project",
+    "FAILED_TO_CREATE_PROJECT": "Failed to create a new project.",
+    "FAILED_TO_DELETE_PROJECT": "Failed to delete the project.",
+    "RENAME_PROJECT": "Rename Project",
+    "COPY_PROJECT": "Copy Project",
+    "NAME": "Name",
+    "ACTIONS": "Actions",
+    "DELETE_PROJECT_CONFIRM": "Delete {projectName}?",
```
Comment (lizlooney) [inline src/i18n/locales/en/translation.json:54]: {projectName} -> {{projectName}}

File: src/i18n/locales/en/translation.json [hunk 8]
```diff
@@ -42,6 +43,30 @@
...
+    "DELETE_CANNOT_BE_UNDONE": "This action cannot be undone.",
+    "NO_PROJECTS_FOUND": "No projects found",
+    "CREATE_PROJECT_TO_START": "Please create a new project to get started.",
+    "PAGINATION_ITEMS": "{range0}-{range1} of {total} items",
```
Comment (lizlooney) [inline src/i18n/locales/en/translation.json:58]: {range0} -> {{range0}}
{range1} -> {{range1}}
{total} -> {{total}}

File: src/reactComponents/FileManageModal.tsx [hunk 9]
```diff
@@ -441,6 +456,23 @@ export default function FileManageModal(props: FileManageModalProps) {
             onDoubleClick: () => handleRowDoubleClick(record),
           })}
         />
+        <br />        
+        <div style={{
```
Comment (lizlooney) [inline src/reactComponents/FileManageModal.tsx:460]: Can you put "Create a new {{type}}" here? If that's not possible, then "Create New" would be ok.

**Review by lizlooney — CHANGES_REQUESTED** [review]
